{
 "title": "Cardano Node",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cardano_node_metrics_cardano_build_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nodeStartTime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "cardano_node_metrics_nodeStartTime_int",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "slotNum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "blockNum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem_resident",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Mem_resident_int",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}